version: '3.7'
services:
  api:
    container_name: cadastro_cliente_api
    build: ../../src
    image: cadastro_cliente_api
    environment:
      - ConnectionStrings:MySql=Server=dbmysql-cad; Port=3306; Database=cad; Uid=root; Pwd=senha1234;
      - ParametroConsultaCEP:Url=https://viacep.com.br/
      - ParametroConsultaCEP:TemplateResource=ws/{0}/json/
      - ParametroRestConsultaEstado:Url=https://servicodados.ibge.gov.br/api/v1/localidades/estados/
      - ParametroRestConsultaEstado:TemplateResource={0}/municipios
    ports:
      - "8080:80"
    networks:
      - docker-network
    depends_on:
      - elasticsearch
                
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - docker-network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - docker-network
      
volumes:
  elasticsearch-data:
    
networks:
  docker-network:
    driver: bridge

