version: '3.1'
services:
    db:
        container_name: db-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: senha1234
        build:
            context: ./mysql
            dockerfile: Dockerfile
        ports:
            - "3306:3306"